language: scala

env:
  global:
    - REPO="bizreach/elastic-scala-httpclient"
    - CI_HOME=`pwd`/$REPO

script:
  - cd $CI_HOME/elastic-scala-httpclient && sbt test
  - cd $CI_HOME/elastic-scala-codegen && sbt test scripted
